name: Go
on: [pull_request]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Set up Go 1.13
      uses: actions/setup-go@v1
      with:
        go-version: 1.13
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: Cache
      uses: actions/cache@v1.0.3
      with:
        # A directory to store and save the cache
        path: ~/go/pkg/mod
        # An explicit key for restoring and saving the cache
        key: ${{ runner.os }}-go-${{ hashFiles('go.sum') }}
        # An ordered list of keys to use for restoring the cache if no cache hit occurred for key
        restore-keys: ${{ runner.os }}-go-
    - name: Get dependencies
      run: |
        go get -v -t -d ./...
    - name: Build
      run: go build -v ./cmd/git-fzf
    - name: Test
      run: |
        go test -v ./...
        go test -race ./...

  golangci-lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
    - name: Check out code into the Go module directory
      uses: actions/checkout@v1
    - name: GolangCI-Lint Action
      uses: actions-contrib/golangci-lint@v0.1.0
      with:
        args: "run -v ./..."
